spring.application.name=rentalmanager

spring.datasource.url=jdbc:mysql://localhost:3306/rentalmanager
spring.datasource.username=ridehub
spring.datasource.password=ridehub123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082